###
GET http://localhost:3000/users/ HTTP/1.1
###
POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"kahul",
    "username":"kahul123",
    "password": "kahul@456",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"kahul123",
    "password": "kahul@456"
}